<?php
return [
    [
        'menu_name' => '物流系统',
        'menu_key' => 'fengchao',
        'menu_short_name' => '物流',
        'parent_key' => '',
        'menu_type' => '0',
        'icon' => 'iconfont iconyingyongshichang',
        'api_url' => '',
        'router_path' => '',
        'view_path' => '',
        'methods' => '',
        'sort' => '110',
        'status' => '1',
        'is_show' => '1',
        'children' => [
            [
                'menu_name' => '订单管理',
                'menu_key' => 'site_app_order',
                'menu_short_name' => '站点订单',
                'menu_type' => '1',
                'icon' => 'element Money',
                'api_url' => 'fengchao/app/order',
                'router_path' => 'fengchao/app/order',
                'view_path' => 'app/order/index',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '订单详情',
                'menu_key' => 'fengchao_order_detail',
                'menu_short_name' => '订单详情',
                'menu_type' => '1',
                'icon' => 'iconfont iconshangpinguanli',
                'api_url' => 'fengchao/app/order/detail/<id>',
                'router_path' => 'fengchao/order/detail',
                'view_path' => 'app/order/detail',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '站点余额',
                'menu_key' => 'site_app_balance',
                'menu_short_name' => '站点余额',
                'menu_type' => '1',
                'icon' => 'element Money',
                'api_url' => 'fengchao/site/balance',
                'router_path' => 'fengchao/site/balance',
                'view_path' => 'app/balance/index',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => 'API接口',
                'menu_key' => 'site_app_api',
                'menu_short_name' => 'API',
                'menu_type' => '1',
                'icon' => 'element Money',
                'api_url' => 'fengchao/api/manage',
                'router_path' => 'fengchao/api/manage',
                'view_path' => 'app/api/index',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '1',
            ],
            [
                'menu_name' => '沙盒测试',
                'menu_key' => 'app_api_sandbox',
                'menu_short_name' => '沙盒测试',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'fengchao/api/sandbox/<id>',
                'router_path' => 'fengchao/api/sandbox',
                'view_path' => 'app/api/sandbox',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
            [
                'menu_name' => '沙盒测试callback',
                'menu_key' => 'app_api_sandbox_callback',
                'menu_short_name' => '沙盒测试callback',
                'menu_type' => '1',
                'icon' => '',
                'api_url' => 'fengchao/api/sandbox1/<id>',
                'router_path' => 'fengchao/api/sandbox1',
                'view_path' => 'app/api/callback',
                'methods' => 'get',
                'sort' => '0',
                'status' => '1',
                'is_show' => '0',
            ],
        ],
    ],
];